apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-observability-agent.fullname" . }}
  labels:
    {{- include "k8s-observability-agent.labels" . | nindent 4 }}
type: Opaque
data:
  slack-token: {{ .Values.config.secrets.slackToken | b64enc | quote }}
  openai-key: {{ .Values.config.secrets.openaiKey | b64enc | quote }}
  github-token: {{ .Values.config.secrets.githubToken | b64enc | quote }}
